type: custom:button-card
name: false
entity: light.kitchen
icon: mdi:ceiling-light
show_icon: false
styles:
  card:
    - background-color: '#35425c'
    - border-radius: 20px
    - padding-left: 9px
    - box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px
  name:
    - font-size: 13px
  grid:
    - grid-template-areas: '"b1 b2 b3 b4 b5 "'
    - grid-template-columns: 1fr 1fr 1fr 1fr  1fr
    - grid-template-rows: 1fr
custom_fields:
  b1:
    card:
      type: custom:button-card
      show_name: true
      name: Power
      icon: mdi:toggle-switch
      styles:
        name:
          - font-size: 10px
          - padding-bottom: 5px
        card:
          - background-color: '#2b374e'
          - border-style: none
          - border-radius: 15px
          - width: 65px
          - height: 65px
        icon:
          - align-self: start
          - text-align: start
          - color: white
  b2:
    card:
      type: custom:button-card
      show_name: true
      name: Lamps
      icon: mdi:lamps
      styles:
        name:
          - font-size: 10px
          - padding-bottom: 5px
        card:
          - background-color: '#2b374e'
          - border-style: none
          - border-radius: 15px
          - width: 65px
          - height: 65px
        icon:
          - align-self: start
          - text-align: start
          - color: white
  b3:
    card:
      type: custom:button-card
      show_name: true
      name: Ceiling
      icon: mdi:ceiling-light-multiple
      styles:
        name:
          - font-size: 10px
          - padding-bottom: 5px
        card:
          - background-color: '#2b374e'
          - border-style: none
          - border-radius: 15px
          - width: 65px
          - height: 65px
        icon:
          - align-self: start
          - text-align: start
          - color: white
          - opacity: 0.4
  b4:
    card:
      type: custom:button-card
      show_name: true
      name: Brightness
      icon: mdi:theme-light-dark
      styles:
        name:
          - font-size: 10px
          - padding-bottom: 5px
        card:
          - background-color: '#2b374e'
          - border-style: none
          - border-radius: 15px
          - width: 65px
          - height: 65px
        icon:
          - align-self: start
          - text-align: start
          - color: white
  b5:
    card:
      type: custom:button-card
      show_name: true
      name: Motion
      icon: mdi:motion-sensor
      styles:
        name:
          - font-size: 10px
          - padding-bottom: 5px
        card:
          - background-color: '#2b374e'
          - border-style: none
          - border-radius: 15px
          - width: 65px
          - height: 65px
        icon:
          - align-self: start
          - text-align: start
          - color: white

